# Generated by Django 4.2.16 on 2026-04-12 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=255, verbose_name='Pessoa de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Local')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chapa', models.IntegerField(help_text='Identificador único do item (ex: 1001)', unique=True, verbose_name='Número da Chapa')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('baixado', 'Baixado')], default='ativo', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, max_length=255, verbose_name='Responsável')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.fornecedor', verbose_name='Fornecedor')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Item Patrimonial',
                'verbose_name_plural': 'Itens Patrimoniais',
                'ordering': ['numero_chapa'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('DELETAR', 'Deletar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORTAR', 'Importar')], max_length=20, verbose_name='Ação')),
                ('tipo_entidade', models.CharField(choices=[('PATRIMONIO', 'Patrimônio'), ('FORNECEDOR', 'Fornecedor'), ('LOCALIZACAO', 'Localização'), ('USUARIO', 'Usuário'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario_nome', models.CharField(max_length=255, verbose_name='Nome do Usuário')),
                ('entidade_id', models.CharField(blank=True, max_length=50, verbose_name='ID da Entidade')),
                ('entidade_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome da Entidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
