# Generated by Django 4.2.16 on 2026-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioitem',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
    ]
