# Migration gerada automaticamente a partir do arquivo "Inventario 2026.xlsx"
from django.db import migrations

LOCALIZACOES = [
    "AGENCIA DE PUBLICIDADE",
    "Aguardando Localizacao - Labinfo 2025",
    "Aguardando Localização",
    "Almox Labinfo",
    "ALMOXARIFADO",
    "ALMOXARIFADO BIBLIOTECA",
    "ALMOXARIFADO DO BLOCO 7",
    "ALMOXARIFADO DO BLOCO 9 - ESCADARIA",
    "ALMOXARIFADO TV/RADIO",
    "ALOJAMENTO FEMININO",
    "ALOJAMENTO MASCULINO",
    "ANFITEATRO",
    "Anfiteatro Bloco 12",
    "ANTENA RADIO FEMA",
    "APOIO A MANUTENCAO/JARDINAGEM (GRADIL)",
    "AQUARIO TV",
    "Auditorio",
    "BIBLIOTECA - Acervo",
    "BIBLIOTECA - PARTE MOBILIARIO E AFINS",
    "BIBLIOTECA - SALA DA BIBLIOTECARIA",
    "Bloco 1 - Inventario 2026",
    "Bloco 10 - Inventario",
    "Bloco 10 - Recepção de Itens",
    "Bloco 12",
    "Bloco 12 - Corredor Terreo",
    "Bloco 12 - Sala da Coordenacao",
    "Bloco 12 - Sala dos Professores",
    "Bloco 12 - Salão Térreo",
    "Bloco 12 - Secretaria",
    "Bloco 12 - Secretaria - Arquivo",
    "BLOCO 2 - CEPECI",
    "Bloco 4 - Inventario 2026",
    "Bloco 4 - Recepção de Itens",
    "BLOCO 5 - BLOCO 5",
    "BLOCO 6 - FEMANET",
    "Bloco 7 - Laboratorio de Informatica - Mudanca de Salas (Inventario)",
    "Bloco 7 - Mudanca de Salas (Inventario)",
    "Bloco 8 - Recepção de Itens",
    "Bloco 9 - Corredor 1 andar",
    "Bloco 9 - Corredor 2 andar",
    "Bloco 9 - Recepção de Itens",
    "BONFIM - CORREDOR",
    "BONFIM - SALA 1",
    "BONFIM - SALA 2",
    "BONFIM - SALA 3",
    "BONFIM - SALA 4",
    "BONFIM - SALA 5",
    "BONFIM - SALA DE REUNIÃO",
    "CASA DA CRIANÇA - EMPRÉSTIMOS",
    "CENTRO DE ESPECIALIDADES",
    "CENTRO DE ESPECIALIDADES. - CONSULTORIO 1",
    "CENTRO DE ESPECIALIDADES. - CONSULTORIO 2",
    "CENTRO DE ESPECIALIDADES. - CONSULTORIO 3",
    "CENTRO DE ESPECIALIDADES. - CONSULTORIO 4",
    "CENTRO DE ESTUDOS SANTA CASA - FEMA",
    "CEPECI",
    "CEPEIN",
    "CEPEIN - DESENVOLVIMENTO DE SISTEMAS",
    "CEPEIN - FEMANET",
    "CEPEIN - HARDWARE",
    "CEPEIN - ITENS NAO ENCONTRADOS",
    "CEPEIN - RESERVA",
    "CIEE - ANTIGO ALMOXARIFADO DO BLOCO 7",
    "CINE PIRACAIA",
    "COHAB IV - CORREDOR",
    "COHAB IV - SALA 1",
    "COHAB IV - SALA 2",
    "COHAB IV - SALA 3",
    "COHAB IV - SALA 4",
    "COHAB IV - SALA 5",
    "COHAB IV - SALA DE REUNIÃO",
    "COMITE DE ETICA EM PESQUISA",
    "CONTABIL",
    "CONTABIL/TESOURARIA/RH BEN/DEPTO PESSOAL",
    "COORDENADORIA - COORDENADORES",
    "COPA",
    "CORREDOR",
    "Corredor Bloco 10",
    "Corredor Bloco 12 - 2 andar",
    "Corredor Medicina - Primeiro andar",
    "Corredor Medicina - Segundo andar",
    "DEPARTAMENTO JURIDICO",
    "DEPOSITO DE INSERVIVEIS",
    "Deposito de inserviveis 2",
    "DIRECAO DO IMESA",
    "DIRETORIA EXECUTIVA",
    "Docente",
    "EMPRESTIMOS",
    "ENFERMAGEM/FISIOTERAPIA - COORDENAÇÃO",
    "ENFERMAGEM/FISIOTERAPIA - LABORATORIO DE MORFOLOGIA",
    "Especialidades",
    "Eventos/Copinha-Anfiteratro",
    "Eventos/Copinha/anfiteatro",
    "FEMA JUNIOR",
    "Fema Patrimônio - Recepção de Mercadorias",
    "FINANCEIRO",
    "FISIOTERAPIA - Atendimento Fisioterapia - Corredor 1 andar",
    "FISIOTERAPIA - CONSULTORIO 1",
    "FISIOTERAPIA - CONSULTORIO 2",
    "FISIOTERAPIA - FISIOTERAPIA",
    "Fisioterapia - Fisioterapia Respiratoria",
    "FISIOTERAPIA - Ginecologia/Urologia/Mastologia",
    "FISIOTERAPIA - LABORATORIO DE AVALIACAO FUNCIONAL",
    "FISIOTERAPIA - LABORATORIO DE PRATICAS DE FISIOTERAPIA",
    "FISIOTERAPIA - LABORATORIO DE PRATICAS DE FISIOTERAPIA II",
    "FISIOTERAPIA - REABILITACAO CARDIACA",
    "FISIOTERAPIA - SALA DE TECNOLOGIA ASSISTIVA",
    "FISIOTERAPIA - SETOR DE NEUROLOGIA",
    "FISIOTERAPIA - SETOR DE ORTOPEDIA",
    "FISIOTERAPIA -Ginecologia/Urologia/Mastologia",
    "HALL DO ANFITEATRO",
    "Hospital Regional de Assis",
    "Hub",
    "HUB INOVA",
    "IMOVEIS - CONSTRUÇÕES",
    "IMOVEIS - TERRENO",
    "INSTALACOES",
    "INTERNATO SANTA CASA",
    "Inventario 2023 - Sala Ficticia",
    "Inventario 2025 - Bloco 1 - Sala Ficticia",
    "Inventario 2025 - Bloco 10 - Sala Ficticia",
    "Inventario 2025 - Bloco 4 - Sala Ficticia",
    "Inventario 2026 - Jardim Parana",
    "Inventario 2026 - Vila Operária",
    "Itens Nao Localizados",
    "Itens não Localizados",
    "JARDIM PARANA - CORREDOR",
    "JARDIM PARANA - SALA 1",
    "JARDIM PARANA - SALA 2",
    "JARDIM PARANA - SALA 3",
    "JARDIM PARANA - SALA 4",
    "JARDIM PARANA - SALA 5",
    "JARDIM PARANA - SALA DE REUNIÃO",
    "JARDIM PARANA - SALA RECEPÇÃO",
    "JD. ELDORADO - SALA FEMA",
    "LAB QUIMICA - EXTERNA",
    "Laboratorio Audiovisual 1",
    "LABORATORIO DE COMUNICACAO - ALMOXARIFADO",
    "LABORATORIO DE COMUNICACAO - AUDIO",
    "LABORATORIO DE COMUNICACAO - ESTUDIO",
    "LABORATORIO DE ENFERMAGEM",
    "LABORATORIO DE FISICA E ELETRONICA",
    "LABORATORIO DE FOTOGRAFIA - ESTUDIO DE FOTOGRAFIA",
    "LABORATORIO DE INFORMATICA - ALMOX",
    "LABORATORIO DE INFORMATICA - ALMOXARIFADO",
    "LABORATORIO DE INFORMATICA - RECEPÇÃO",
    "LABORATORIO DE INFORMATICA - SALA A",
    "LABORATORIO DE INFORMATICA - SALA B",
    "LABORATORIO DE INFORMATICA - SALA C",
    "LABORATORIO DE INFORMATICA - SALA D",
    "LABORATORIO DE INFORMATICA - SALA E",
    "LABORATORIO DE INFORMATICA - SALA F",
    "LABORATORIO DE INFORMATICA - SALAB",
    "Laboratorio de Maquetes",
    "LABORATORIO DE QUIMICA - ALMOXARIFADO 1",
    "LABORATORIO DE QUIMICA - ALMOXARIFADO 2",
    "LABORATORIO DE QUIMICA - ALMOXARIFADO 3",
    "LABORATORIO DE QUIMICA - ANALITICA",
    "LABORATORIO DE QUIMICA - COORDENADORIA",
    "LABORATORIO DE QUIMICA - MICROBIOLOGIA",
    "LABORATORIO DE QUIMICA - PIC",
    "LABORATORIO DE QUIMICA - SALA A",
    "LABORATORIO DE QUIMICA - SALA B",
    "LABORATORIO DE QUIMICA - SALA C",
    "LABORATORIO DE REDES",
    "Laboratório de Maquetes",
    "Licitacoes",
    "Licitações",
    "Mantenadora - Recepção 1",
    "Mantenedora - Recepção 2",
    "MANTENEDORA - SECRETARIA",
    "MANTENEDORA RECEPCAO",
    "MANUTENCAO",
    "Marketing",
    "MEDICINA",
    "MEDICINA - ALMOXARIFADO",
    "Medicina - Coordenacao NDE",
    "MEDICINA - COPA",
    "MEDICINA - CORREDOR",
    "Medicina - Corredor OSC",
    "Medicina - Laboratorios de Morfologia (A/B)",
    "Medicina - Laboratorios de Morfologia A",
    "Medicina - Laboratorios de Morfologia B",
    "Medicina - Laboratorios de MorfologiaB",
    "Medicina - Mudanca de Salas Inventario",
    "MEDICINA - NDE",
    "Medicina - OSC A",
    "Medicina - OSC B",
    "Medicina - OSC C",
    "Medicina - OSC D",
    "Medicina - OSC E",
    "Medicina - OSC F",
    "Medicina - Sala 09 - H",
    "Medicina - Sala 10 - H",
    "Medicina - Sala 11 - I",
    "Medicina - Sala 11- I",
    "Medicina - Sala 12 - I",
    "Medicina - Sala 13 - J",
    "Medicina - Sala 14 - J",
    "Medicina - Sala de Domicilio",
    "MEDICINA - SALA DE SIMULAÇÃO DE EMERGENCIA",
    "MEDICINA - SALA DE TÉCNICAS CIRÚRGICAS",
    "Medicina - Sala Multiuso A",
    "Medicina - Sala Professores 1",
    "Medicina - Sala Professores 2",
    "MEDICINA - SECRETARIA",
    "NAO LOCALIZADO",
    "Necrim",
    "Nucleo Audiovisual 1",
    "Nucleo Audiovisual 2",
    "NUCLEO DE PRATICA JURIDICA",
    "Planejamento",
    "PMA - AUTARQUIA MUNI ESPORTE-EMPRES",
    "PMA - ENSINO PROFISSIONAL-EMPRESTIM",
    "PORTARIA GETULIO VARGAS",
    "PORTARIA SAO CRISTOVAO",
    "PREFEITURA - PAÇO PREFEITURA",
    "Prudenciana - CORREDOR",
    "Prudenciana - SALA 1",
    "Prudenciana - SALA 2",
    "Prudenciana - SALA 3",
    "Prudenciana - SALA 4",
    "Prudenciana - SALA 5",
    "Prudenciana - SALA DE REUNIÃO",
    "RADIO FEMA E AQUARIO",
    "RECEPÇÃO DO IMESA",
    "RECURSOS HUMANOS",
    "Refeitorio",
    "RH - BENEFICIOS",
    "SALA  41",
    "SALA  42",
    "SALA 101",
    "SALA 102",
    "Sala 1021",
    "SALA 103",
    "SALA 104",
    "SALA 105",
    "SALA 106",
    "SALA 107",
    "SALA 11",
    "SALA 12",
    "Sala 1201",
    "Sala 1203",
    "Sala 1203 (Laboratorio da Engenharia Civil)",
    "Sala 1204",
    "Sala 121",
    "Sala 1211",
    "Sala 122",
    "Sala 122 B",
    "Sala 123",
    "Sala 124",
    "SALA 125B",
    "SALA 126B",
    "SALA 127B",
    "SALA 128B",
    "Sala 13",
    "SALA 14",
    "SALA 15",
    "SALA 41",
    "SALA 42",
    "SALA 43",
    "SALA 44",
    "SALA 45",
    "SALA 46",
    "SALA 81",
    "SALA 82",
    "SALA 83",
    "SALA 84",
    "SALA 90B",
    "SALA 91",
    "SALA 91B",
    "SALA 92",
    "SALA 92B",
    "SALA 93",
    "SALA 93B",
    "SALA 94",
    "SALA 94B",
    "SALA 95B",
    "SALA 96B",
    "SALA 97B",
    "SALA 98 B",
    "SALA 99 B",
    "Sala da Coordenação",
    "SALA DA PRESIDENCIA",
    "SALA DAS FAXINEIRAS BLOCO 9",
    "SALA DAS TERCEIRIZADAS",
    "Sala de Coordenação de Informática",
    "SALA DE IMPRESSÃO",
    "SALA DOS PROFESSORES",
    "SANITARIO MASCULINO",
    "SECAO ALUNOS",
    "SECAO DE ALUNOS",
    "SECAO DE EVENTOS",
    "SECAO DOCENTE",
    "SECRETARIA DO IMESA",
    "SERVICOS GERAIS",
    "Setor de Patrimonio",
    "SETOR DE REPROGRAFIA",
    "Setor Reprografia",
    "SETOR VESTIBULAR",
    "SUPERVISAO ACADEMICA",
    "TELEFONIA",
    "TESOURARIA",
    "TV FEMA",
    "UPA",
    "UPA - ADMINISTRACAO",
    "UPA - ALMOXARIFADO",
    "UPA - ATENDIMENTO SOCIAL",
    "UPA - CONSULTORIO 1",
    "UPA - CONSULTORIO 2",
    "UPA - CONSULTORIO 3",
    "UPA - CONSULTORIO 4",
    "UPA - COORDENACAO",
    "UPA - COORDENACAO MEDICA",
    "UPA - COPA",
    "UPA - CPD/TI",
    "UPA - DEPOSITO DE PATRIMONIO",
    "UPA - Dormitorio",
    "UPA - EMERGENCIA",
    "UPA - EXPURGO",
    "UPA - FARMACIA",
    "UPA - IMOBILIZACAO - GESSO",
    "UPA - ISOLAMENTO 1",
    "UPA - ISOLAMENTO 2",
    "UPA - LABORATORIO 4",
    "UPA - MONITORAMENTO",
    "UPA - OBSERVACAO FEMININA",
    "UPA - OBSERVACAO MASCULINO",
    "UPA - POSTO DE ENFERMAGEM",
    "UPA - RAIO X",
    "UPA - RECEPCAO",
    "UPA - SALA DE COLETA",
    "UPA - SALA DE EQUIPAMENTOS",
    "UPA - SALA DE MEDICAO RAPIDA",
    "UPA - SALA DE SUTURA",
    "UPA - TELEMEDICINA",
    "UPA - TRIAGEM",
    "VICE DIRETORIA",
    "Vila Maria Isabel - CORREDOR",
    "Vila Maria Isabel - SALA 1",
    "Vila Maria Isabel - SALA 2",
    "Vila Maria Isabel - SALA 3",
    "Vila Maria Isabel - SALA 4",
    "Vila Maria Isabel - SALA 5",
    "Vila Maria Isabel - SALA DE REUNIÃO",
    "Vila Operaria - Corredor",
    "Vila Operaria - SALA 1",
    "Vila Operaria - SALA 2",
    "Vila Operaria - SALA 3",
    "Vila Operaria - SALA 4",
    "Vila Operaria - SALA 5",
    "Vila Operaria - SALA 6",
    "Vila Operaria - SALA DE REUNIÃO",
    "VITORIA - CORREDOR",
    "Vitoria - Mudancas de Sala - Inventario",
    "VITORIA - SALA 1",
    "VITORIA - SALA 2",
    "VITORIA - SALA 3",
    "VITORIA - SALA 4",
    "VITORIA - SALA 5",
    "VITORIA - SALA DE REUNIÃO",
]


def populate(apps, schema_editor):
    Localizacao = apps.get_model('patrimonio', 'Localizacao')
    for nome in LOCALIZACOES:
        Localizacao.objects.get_or_create(nome=nome)


def despopulate(apps, schema_editor):
    Localizacao = apps.get_model('patrimonio', 'Localizacao')
    Localizacao.objects.filter(nome__in=LOCALIZACOES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alter_patrimonioitem_categoria'),
    ]

    operations = [
        migrations.RunPython(populate, despopulate),
    ]
