# Generated by Django 4.2.16 on 2026-04-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonio', '0003_populate_localizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonioitem',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='patrimonioitem',
            name='criado_por_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome de quem cadastrou'),
        ),
    ]
