# Generated by Django 4.2.16 on 2026-04-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_add_criado_por_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='XLSReferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chapa', models.IntegerField(unique=True, verbose_name='Número da Chapa')),
                ('nome', models.CharField(blank=True, max_length=500, verbose_name='Nome/Descrição')),
                ('data_aquisicao', models.CharField(blank=True, max_length=10, verbose_name='Data (ISO)')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local 2')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Item XLS Referência',
                'verbose_name_plural': 'Itens XLS Referência',
            },
        ),
    ]
