# Generated by Django 5.0.14 on 2026-06-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_manutencao_solicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('DELETAR', 'Deletar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORTAR', 'Importar'), ('TRANSFERIR', 'Transferir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.CreateModel(
            name='PermissaoConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferentes', to='patrimonio.localizacao', verbose_name='Localização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_conferencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Conferência',
                'verbose_name_plural': 'Permissões de Conferência',
                'ordering': ['usuario__username', 'localizacao__nome'],
                'unique_together': {('usuario', 'localizacao')},
            },
        ),
    ]
